[package]
name = "live"
version = "0.1.0"
authors = ["Igor Poloskov <ipoloskov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
neuronet = { git = "https://github.com/poloskovi/neuronet", version = ">=0.1.1"}
#neuronet = { file = "../neuronet" }
